services:

  get_set_method_normalizer:
    class: Symfony\Component\Serializer\Normalizer\GetSetMethodNormalizer
    tags: [ serializer.normalizer ]

  app.jlob.serializer:
    class: Symfony\Component\Serializer\Serializer
    arguments:
      $normalizers:
        - '@get_set_method_normalizer'
      $encoders:
        - '@serializer.encoder.json'

  App\EventSubscriber\JSONBDeserializerListener:
    class: App\EventSubscriber\JSONBDeserializerListener
    arguments:
      - '@property_accessor'
      - '@app.jlob.serializer'
    tags:
      - { name: doctrine.event_listener, event: postLoad }

  App\Form\DataTransformer\JlobObjectToTextEditTransformer:
    class: App\Form\DataTransformer\JlobObjectToTextEditTransformer
    arguments:
      - '@app.jlob.serializer'