monolog:
    handlers:
        main:
            type: fingers_crossed
            action_level: error
            handler: graylog
            excluded_http_codes: [404, 405]
            channels: ['!event']
        graylog:
            type: gelf
            publisher: { id: 'gelf.publisher' }
            formatter: 'monolog.formatter.gelf_message'
            level: info
        local_files:
            type: rotating_file
            path: "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug
            max_files: 3

        # uncomment to get logging in your browser
        # you may have to allow bigger header sizes in your Web server configuration
        #firephp:
        #    type: firephp
        #    level: info
        #chromephp:
        #    type: chromephp
        #    level: info
        console:
            type: console
            process_psr_3_messages: false
            channels: ["!event", "!doctrine", "!console"]


