services:
    _defaults:
        public: false
        autowire: true
        autoconfigure: true

    # Uncomment any lines below to activate that Twig extension
    #Twig\Extensions\ArrayExtension: null
    #Twig\Extensions\DateExtension: null # заменил на knp-time-bundle умеющим в локализацию
    Twig\Extensions\IntlExtension: null
    Twig\Extensions\TextExtension: null

    App\Service\Twig\TimeExtension:
        class: App\Service\Twig\TimeExtension
        arguments: ['@time.datetime_formatter', '@translator' ]
        tags:
            - { name: twig.extension }

    time.twig.extension.time:
        alias: App\Service\Twig\TimeExtension
        public: true