twig:
    default_path: '%kernel.project_dir%/templates'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    exception_controller: null
    form_themes: ['bootstrap_3_horizontal_layout.html.twig']

    globals:
        app_version: '%app.version%'
        support_url: '%app.support_url%'
        project_manager: '@App\Service\ProjectManager'
