
services:
  nginx:
    build:
      context: ./
      dockerfile: './docker/nginx.dockerfile'
    links:
      - php
    environment:
      TZ: Europe/Moscow

  php:
    build:
      context: ./
      dockerfile: './docker/php.dockerfile'
    links:
      - mysql
    environment:
      TZ: Europe/Moscow
      DATABASE_URL: "mysql://${DB_USER}:${DB_PASSWORD}@mysql:3306/${DB_NAME}"

  mysql:
    image: 'mysql:5.7'
    environment:
      MYSQL_USER: '${DB_USER}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
      MYSQL_DATABASE: '${DB_NAME}'
