
services:
  nginx:
    build:
      target: 'dev'
    volumes:
      - './docker/dev.nginx.conf:/etc/nginx/conf.d/default.conf'
      - './public:/app/public'
      - './var/storage/dev/files:/data:ro'
      - './var/log/nginx:/var/log/nginx'
    ports:
      - 4001:80

  php:
    build:
      target: 'dev'
    volumes:
      - './:/app'
      - './var/storage/dev/files:/data:rw'
    environment:
      APP_ENV: 'dev'
      APP_DEBUG: 'true'
      GRAYLOG_HOST: '192.168.100.15'
      GRAYLOG_PORT: 12201
      GRAYLOG_TAGNAME: tag
      GRAYLOG_TAG: 'tndt_dev:php'


  mysql:
    volumes:
      - './var/storage/dev/mysql:/var/lib/mysql:rw'
    ports:
      - 4003:3306 # в дев можно подключаться к БД напрямую, например из IDE
    environment:
      MYSQL_ROOT_PASSWORD: '123'
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'

  redis:
    volumes:
      - './var/storage/dev/redis:/data:rw'
    ports:
      - 4004:6379

  pma:
    profiles: [dev]
    image: phpmyadmin/phpmyadmin
    links:
      - mysql
    ports:
      - 4002:80
    environment:
      - "PMA_ARBITRARY=1"
      - "PMA_HOST=mysql"
      - "PMA_PORTS=3306"

  front_builder:
    profiles: [tools]
    build:
      context: './docker/'
      dockerfile: './npm.dockerfile'
    volumes:
      - './:/app'
