
services:
  nginx:
    build:
      context: ./
      dockerfile: './docker/nginx.dockerfile'
    links:
      - php
    environment:
      TZ: Europe/Moscow

  php:
    build:
      context: ./
      dockerfile: './docker/php.dockerfile'
    links:
      - mysql
      - redis
    environment:
      TZ: Europe/Moscow
      DATABASE_URL: "mysql://${DB_USER}:${DB_PASSWORD}@mysql:3306/${DB_NAME}"
      REDIS_URL: "redis"

  mysql:
    image: 'mysql:5.7'
    environment:
      MYSQL_USER: '${DB_USER}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
      MYSQL_DATABASE: '${DB_NAME}'

  redis:
    image: redis:7-alpine
    volumes:
      - './docker/redis.conf:/usr/local/etc/redis/redis.conf:ro'
