
services:
  nginx:
    image: 'demius/tndt.php:latest'
    restart: unless-stopped
    networks:
      web:
        aliases:
          - tndt
      default:
    links:
      - php
    environment:
      TZ: Europe/Moscow

  php:
    image: 'demius/tndt.php:latest'
    restart: unless-stopped
    networks:
      - default
    links:
      - mysql
      - redis
    volumes:
      - 'cache:/app/var/cache'
      - '<hostdir>/etc:/app/config/prod' # если необходимо изменить тонкие настройки системы, например добавить кеширование через memcaсhe
    environment:
      APP_ENV: prod
      TZ: Europe/Moscow
      DATABASE_URL: "mysql://${DB_USER}:${DB_PASSWORD}@mysql:3306/${DB_NAME}"
      REDIS_URL: "redis"

  mysql:
    image: 'mysql:5.7'
    restart: unless-stopped
    networks:
      - default
    volumes:
      - 'storage:/var/lib/mysql:rw'
    environment:
      MYSQL_USER: '${DB_USER}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
      MYSQL_DATABASE: '${DB_NAME}'

  redis:
    image: redis:7-alpine
    volumes:
      - './docker/redis.conf:/usr/local/etc/redis/redis.conf:ro'
      - 'redis:/data:rw'

volumes:
  cache:
  storage:
  redis:

networks:
  web:
    external: true
  default:
    external: false