
services:
  nginx:
    image: 'demius/tndt.php:latest'
    restart: unless-stopped
    networks:
      web:
        aliases:
          - tndt
      default:
    links:
      - php
    environment:
      TZ: Europe/Moscow

  php:
    image: 'demius/tndt.php:latest'
    restart: unless-stopped
    networks:
      - default
    links:
      - mysql
    volumes:
      - 'cache:/app/var/cache'
      - '<hostdir>/etc:/app/config/prod' # если необходимо изменить тонкие настройки системы, например добавить кеширование через memcaсhe
    environment:
      APP_ENV: prod
      TZ: Europe/Moscow
      DATABASE_URL: "mysql://${DB_USER}:${DB_PASSWORD}@mysql:3306/${DB_NAME}"

  mysql:
    image: 'mysql:5.7'
    restart: unless-stopped
    networks:
      - default
    volumes:
      - 'storage:/var/lib/mysql:rw'
    environment:
      MYSQL_USER: '${DB_USER}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
      MYSQL_DATABASE: '${DB_NAME}'

volumes:
  cache:
  storage:

networks:
  web:
    external: true
  default:
    external: false