version: '3.4'
services:
  nginx:
    image: 'nginx:alpine'
    volumes:
      - './docker/dev.nginx.conf:/etc/nginx/conf.d/default.conf'
      - './public:/app/public'
      - './var/log/nginx:/var/log/nginx'
    ports:
      - 4001:80
    links:
      - php

  php:
    build:
      context: '.'
      dockerfile: './docker/php.dockerfile'
      target: 'dev'
    volumes:
      - './:/app'
#    ports:
#      - 4004:9000

  mysql:
    volumes:
      - './var/storage/dev/mysql:/var/lib/mysql:rw'
    ports:
      - 4003:3306 # в дев можно подключаться к БД напрямую, например из IDE
    environment:
      MYSQL_ROOT_PASSWORD: '123'
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'

  pma:
    image: phpmyadmin/phpmyadmin
    links:
      - mysql
    ports:
      - 4002:80
    environment:
      - "PMA_ARBITRARY=1"
      - "PMA_HOST=mysql"
      - "PMA_PORTS=3306"

  front_builder:
    build:
      context: './docker/'
      dockerfile: './npm.dockerfile'
    volumes:
      - './:/var/www'
