version: '2'
services:
  php:
    build:
      dockerfile: './docker/dev.php.dockerfile'
    volumes:
      - './:/var/www'
    environment:
      APP_ENV: test

  mysql:
    volumes:
      - './var/storage/test/mysql:/var/lib/mysql:rw'
    ports:
      - 4003:3306

  pma:
    image: phpmyadmin/phpmyadmin
    links:
      - mysql
    ports:
      - 4002:80
    environment:
      - "PMA_ARBITRARY=1"
      - "PMA_HOST=mysql"
      - "PMA_PORTS=3306"