version: '3.4'
#Базовый набор сервисов в настройками готовыми для запуска без всего
services:
  nginx:
    image: 'nginx:alpine'
    links:
      - php

  php:
    build:
      context: ./
      dockerfile: './docker/php.dockerfile'
    links:
      - mysql
    environment:
      DATABASE_URL: "mysql://${DB_USER}:${DB_PASSWORD}@mysql:3306/${DB_NAME}"

  mysql:
    image: 'mysql:5.7'
    environment:
      MYSQL_USER: '${DB_USER}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
      MYSQL_DATABASE: '${DB_NAME}'
