version: '2'
services:
  nginx:
    image: 'nginx:alpine'
    volumes:
      - './docker/nginx.conf:/etc/nginx/conf.d/default.conf'
      - './public:/var/www/public'
      - './var/log/nginx:/var/log/nginx'
    ports:
      - 4001:80
    links:
      - php

  php:
    build:
      context: ./
      dockerfile: './docker/dev.php.dockerfile'
    volumes:
      - './:/var/www'
    links:
      - mysql
    environment:
      DATABASE_URL: "mysql://${DB_USER}:${DB_PASSWORD}@mysql:3306/${DB_NAME}"

  mysql:
    image: 'mysql:5.6.43'
    environment:
      MYSQL_ROOT_PASSWORD: '123'
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_USER: '${DB_USER}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
      MYSQL_DATABASE: '${DB_NAME}'
    volumes:
      - './var/mysql:/var/lib/mysql:rw'

  pma:
    image: phpmyadmin/phpmyadmin
    links:
      - mysql
    ports:
      - 4002:80
    environment:
      - "PMA_ARBITRARY=1"
      - "PMA_HOST=mysql"
      - "PMA_PORTS=3306"
