monolog:
    handlers:
        local_files:
            type: rotating_file
            path: "%kernel.logs_dir%/%kernel.environment%.log"
            channels: ['!event']
            level:    debug
            max_files: 5

        # uncomment to get logging in your browser
        # you may have to allow bigger header sizes in your Web server configuration
        #firephp:
        #    type: firephp
        #    level: info
        #chromephp:
        #    type: chromephp
        #    level: info
        console:
            type: console
            process_psr_3_messages: false
            channels: ["!event", "!doctrine", "!console"]
services:

