# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    app.version: 0.3
    app.version_year: 2024
    app.support_url: http://tasks.demius.ru/p/tndt

    mail.sender_user: service@tasks.demius.ru

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.



    # Event Subscribers and Listeners
    App\EventSubscriber\:
        resource: '%kernel.project_dir%/src/EventSubscriber'

#    App\EventSubscriber\NoGeneratorListener:
#        class: App\EventSubscriber\NoGeneratorListener
#        tags:
#            - { name: doctrine.event_listener, event: prePersist }


    # Services @todo separate to different config in tndt-85
    App\Service\:
        resource: '%kernel.project_dir%/src/Service'

    App\Service\ProjectContext:
        class: 'App\Service\ProjectContext'
        calls:
            - findCurrentProject: []

    app.project_context:
        alias: App\Service\ProjectContext


    App\Service\Badges\DocBadgesHandler:
        class: 'App\Service\Badges\DocBadgesHandler'
        tags: ['app.badges_handler']

    App\Service\Badges\TaskBadgesHandler:
        class: 'App\Service\Badges\TaskBadgesHandler'
        tags: ['app.badges_handler']

    App\Service\Badges\UserBadgesHandler:
        class: 'App\Service\Badges\UserBadgesHandler'
        tags: ['app.badges_handler']

    # @todo move to presentation in tndt-85
    App\Service\Twig\BadgesExtension:
        class: 'App\Service\Twig\BadgesExtension'
        arguments:
            - !tagged_iterator app.badges_handler

    App\Service\Twig\TimeExtension:
        class: 'App\Service\Twig\TimeExtension'
        arguments:
            - '@time.datetime_formatter'
            - '@translator.default'
            - '@twig.extension.intl'