services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    App\Repository\:
        resource: '%kernel.project_dir%/src/Repository'

    redis_client.cache:
        class: \Redis
        calls:
            - connect:
                  $host: '%env(REDIS_URL)%'
            - select: [0]

    redis_client.session:
        class: \Redis
        calls:
            - connect:
                $host: '%env(REDIS_URL)%'
            - select: [1]

    Symfony\Component\HttpFoundation\Session\Storage\Handler\RedisSessionHandler:
        arguments:
            - '@redis_client.session'

    monolog.handler.graylog:
        class: Monolog\Handler\GelfHandler
        arguments:
            $publisher: '@gelf.publisher'

    App\Service\Monolog\AddTagProcessor:
        arguments:
            - '%env(GRAYLOG_TAG)%'
            - '%env(GRAYLOG_TAGNAME)%'
        tags:
            - { name: 'monolog.processor', handler: 'graylog'}

    monolog.formatter.gelf_message:
        class: Monolog\Formatter\GelfMessageFormatter

    gelf.publisher:
        class: Gelf\Publisher
        arguments:
            $transport:  '@gelf.transport.udp'

    gelf.transport.udp:
        class: Gelf\Transport\UdpTransport
        arguments:
          $host: '%env(GRAYLOG_HOST)%'
          $port: '%env(GRAYLOG_PORT)%'
