framework:
    cache:
        # Put the unique name of your app here: the prefix seed
        # is used to compute stable namespaces for cache keys.
        #prefix_seed: your_vendor_name/app_name

        # The app cache caches to the filesystem by default.
        # Other options include:

        # Redis
        #app: cache.adapter.redis
        default_redis_provider: 'redis://%env(REDIS_URL)%'
        app: cache.adapter.redis
        system: cache.adapter.system

        # Namespaced pools use the above "app" backend by default
        pools:
            cache.statistics:
                adapter: cache.app

            cache.doctrine.orm.default.query:
                adapter: cache.app
            doctrine.result_cache_pool:
                adapter: cache.app
            doctrine.system_cache_pool:
                adapter: cache.system