doctrine_migrations:
    migrations_paths:
        'App\Migrations': '%kernel.project_dir%/src/Migrations'

    storage:
        table_storage:
            table_name: migration_versions
            version_column_length: 1024
