twig:
    default_path: '%kernel.project_dir%/templates'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    exception_controller: null
    form_themes:
        - '@AdminLTE/layout/form-theme-horizontal.html.twig'
        - 'form_types_theme.html.twig'
#        - '@TetranzSelect2Entity/Form/fields.html.twig'

    globals:
        app_version: '%app.version%'
        app_version_year: '%app.version_year%'
        support_url: '%app.support_url%'

        project_context: '@app.project_context'

services:
    App\Service\Twig\TimeExtension:
        class: App\Service\Twig\TimeExtension
        arguments: ['@time.datetime_formatter', '@translator',  '@twig.extension.intl']
        tags:
            - { name: twig.extension }

    time.twig.extension.time:
        alias: App\Service\Twig\TimeExtension
        public: true
