#Common
home:
    path: /
    controller: App\Controller\DashboardController::index
about:
    path: /about
    controller: App\Controller\DashboardController::about

#Auth
app.login:
    path: /auth/login
    controller: App\Controller\AuthController:login
app.logout:
    path: /auth/logout
    controller: App\Controller\AuthController:logout

#User
user.profile:
    path: /user/profile
    controller: App\Controller\UserController::profile

#Projects
project.index:
    path: /p/{suffix<\w+>}
    controller: App\Controller\ProjectController::index
project.list:
    path: /project/list
    controller: App\Controller\ProjectController::list
project.create:
    path: /project/create
    controller: App\Controller\ProjectController::create
project.edit:
    path: /project/{suffix<\w+>}/edit
    controller: App\Controller\ProjectController::edit
project.archive:
    path: /project/{suffix<\w+>}/archive
    controller: App\Controller\ProjectController::archive

#Tasks
task.list:
    path: /p/{suffix<\w+>}/tasks
    controller: App\Controller\TaskController::list
task.index:
    path: /p/{taskId<\w+-\d+>}
    controller: App\Controller\TaskController::index
task.global_create:
    path: /task/create
    controller: App\Controller\TaskController::create
task.project_create:
    path: /p/{suffix<\w+>}/task/create
    controller: App\Controller\TaskController::create
task.edit:
    path: /p/{taskId<\w+-\d+>}/edit
    controller: App\Controller\TaskController::edit
task.close:
    path: /p/{taskId<\w+-\d+>}/close
    controller: App\Controller\TaskController::close

#Docs
doc.list:
    path: /p/{suffix<\w+>}/docs
    controller: App\Controller\DocController::list
doc.global_create:
    path: /doc/create
    controller: App\Controller\DocController::create
doc.project_create:
    path: /p/{suffix<\w+>}/doc/create
    controller: App\Controller\DocController::create
doc.index:
    path: /p/{suffix<\w+>}/doc/{slug<[\w\d-]+>}
    controller: App\Controller\DocController::index
doc.edit:
    path: /p/{suffix<\w+>}/doc/{slug<[\w\d-]+>}/edit
    controller: App\Controller\DocController::edit
doc.archive:
    path: /p/{suffix<\w+>}/doc/{slug<[\w\d-]+>}/archive
    controller: App\Controller\DocController::archive
