#Common
home:
    path: /
    controller: App\Controller\DashboardController::index

#Auth
#login:
#    path: /auth/login

#User

#Projects
project.index:
    path: /p/{suffix}
    controller: App\Controller\ProjectController::index
project.list:
    path: /project/list
    controller: App\Controller\ProjectController::list
project.create:
    path: /project/create
    controller: App\Controller\ProjectController::create
project.edit:
    path: /project/{suffix}/edit
    controller: App\Controller\ProjectController::edit

#Tasks
