# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    app.version: 0.1
    app.support_url: http://tasks.demius.ru/p/tndt

    mail.sender_user: service@tasks.demius.ru

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Exception,Migrations,Tests,Kernel.php}'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    # Event Subscribers and Listeners
    App\EventSubscriber\NoGeneratorListener:
        class: App\EventSubscriber\NoGeneratorListener
        tags:
            - { name: doctrine.event_listener, event: prePersist }

    # Various Services
    App\Service\ProjectManager:
        class: 'App\Service\ProjectManager'
        calls:
            - findCurrentProject: []

    project_manager:
        alias: App\Service\ProjectManager

    App\Security\Hierarchy\HierarchyHelper:
        class: 'App\Security\Hierarchy\HierarchyHelper'
#        arguments:
#            - '@cache.permissions.adapter'
        configurator: ['@App\Security\Hierarchy\HierarchyConfigurator', 'configure']

